// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.33.2
// source: scraper.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FilterConfigService_GetActiveFilters_FullMethodName = "/scraper.FilterConfigService/GetActiveFilters"
)

// FilterConfigServiceClient is the client API for FilterConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ------------------------------------
// Service hosted by .NET API
// ------------------------------------
type FilterConfigServiceClient interface {
	GetActiveFilters(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*FilterRulesResponse, error)
}

type filterConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFilterConfigServiceClient(cc grpc.ClientConnInterface) FilterConfigServiceClient {
	return &filterConfigServiceClient{cc}
}

func (c *filterConfigServiceClient) GetActiveFilters(ctx context.Context, in *EmptyRequest, opts ...grpc.CallOption) (*FilterRulesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FilterRulesResponse)
	err := c.cc.Invoke(ctx, FilterConfigService_GetActiveFilters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FilterConfigServiceServer is the server API for FilterConfigService service.
// All implementations must embed UnimplementedFilterConfigServiceServer
// for forward compatibility.
//
// ------------------------------------
// Service hosted by .NET API
// ------------------------------------
type FilterConfigServiceServer interface {
	GetActiveFilters(context.Context, *EmptyRequest) (*FilterRulesResponse, error)
	mustEmbedUnimplementedFilterConfigServiceServer()
}

// UnimplementedFilterConfigServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFilterConfigServiceServer struct{}

func (UnimplementedFilterConfigServiceServer) GetActiveFilters(context.Context, *EmptyRequest) (*FilterRulesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActiveFilters not implemented")
}
func (UnimplementedFilterConfigServiceServer) mustEmbedUnimplementedFilterConfigServiceServer() {}
func (UnimplementedFilterConfigServiceServer) testEmbeddedByValue()                             {}

// UnsafeFilterConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FilterConfigServiceServer will
// result in compilation errors.
type UnsafeFilterConfigServiceServer interface {
	mustEmbedUnimplementedFilterConfigServiceServer()
}

func RegisterFilterConfigServiceServer(s grpc.ServiceRegistrar, srv FilterConfigServiceServer) {
	// If the following call panics, it indicates UnimplementedFilterConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FilterConfigService_ServiceDesc, srv)
}

func _FilterConfigService_GetActiveFilters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FilterConfigServiceServer).GetActiveFilters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FilterConfigService_GetActiveFilters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FilterConfigServiceServer).GetActiveFilters(ctx, req.(*EmptyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FilterConfigService_ServiceDesc is the grpc.ServiceDesc for FilterConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FilterConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scraper.FilterConfigService",
	HandlerType: (*FilterConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetActiveFilters",
			Handler:    _FilterConfigService_GetActiveFilters_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scraper.proto",
}

const (
	ScraperCommandService_ForceScrape_FullMethodName = "/scraper.ScraperCommandService/ForceScrape"
)

// ScraperCommandServiceClient is the client API for ScraperCommandService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ------------------------------------
// Service hosted by Go Scraper
// ------------------------------------
type ScraperCommandServiceClient interface {
	ForceScrape(ctx context.Context, in *ForceScrapeRequest, opts ...grpc.CallOption) (*ForceScrapeResponse, error)
}

type scraperCommandServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewScraperCommandServiceClient(cc grpc.ClientConnInterface) ScraperCommandServiceClient {
	return &scraperCommandServiceClient{cc}
}

func (c *scraperCommandServiceClient) ForceScrape(ctx context.Context, in *ForceScrapeRequest, opts ...grpc.CallOption) (*ForceScrapeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForceScrapeResponse)
	err := c.cc.Invoke(ctx, ScraperCommandService_ForceScrape_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScraperCommandServiceServer is the server API for ScraperCommandService service.
// All implementations must embed UnimplementedScraperCommandServiceServer
// for forward compatibility.
//
// ------------------------------------
// Service hosted by Go Scraper
// ------------------------------------
type ScraperCommandServiceServer interface {
	ForceScrape(context.Context, *ForceScrapeRequest) (*ForceScrapeResponse, error)
	mustEmbedUnimplementedScraperCommandServiceServer()
}

// UnimplementedScraperCommandServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScraperCommandServiceServer struct{}

func (UnimplementedScraperCommandServiceServer) ForceScrape(context.Context, *ForceScrapeRequest) (*ForceScrapeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForceScrape not implemented")
}
func (UnimplementedScraperCommandServiceServer) mustEmbedUnimplementedScraperCommandServiceServer() {}
func (UnimplementedScraperCommandServiceServer) testEmbeddedByValue()                               {}

// UnsafeScraperCommandServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScraperCommandServiceServer will
// result in compilation errors.
type UnsafeScraperCommandServiceServer interface {
	mustEmbedUnimplementedScraperCommandServiceServer()
}

func RegisterScraperCommandServiceServer(s grpc.ServiceRegistrar, srv ScraperCommandServiceServer) {
	// If the following call panics, it indicates UnimplementedScraperCommandServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScraperCommandService_ServiceDesc, srv)
}

func _ScraperCommandService_ForceScrape_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForceScrapeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScraperCommandServiceServer).ForceScrape(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScraperCommandService_ForceScrape_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScraperCommandServiceServer).ForceScrape(ctx, req.(*ForceScrapeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScraperCommandService_ServiceDesc is the grpc.ServiceDesc for ScraperCommandService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScraperCommandService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scraper.ScraperCommandService",
	HandlerType: (*ScraperCommandServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ForceScrape",
			Handler:    _ScraperCommandService_ForceScrape_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scraper.proto",
}
