// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v6.33.2
// source: scraper.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmptyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	mi := &file_scraper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{0}
}

type FilterRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	FilterType    string                 `protobuf:"bytes,3,opt,name=filter_type,json=filterType,proto3" json:"filter_type,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterRule) Reset() {
	*x = FilterRule{}
	mi := &file_scraper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterRule) ProtoMessage() {}

func (x *FilterRule) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterRule.ProtoReflect.Descriptor instead.
func (*FilterRule) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{1}
}

func (x *FilterRule) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *FilterRule) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *FilterRule) GetFilterType() string {
	if x != nil {
		return x.FilterType
	}
	return ""
}

func (x *FilterRule) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type FilterRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*FilterRule          `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterRulesResponse) Reset() {
	*x = FilterRulesResponse{}
	mi := &file_scraper_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterRulesResponse) ProtoMessage() {}

func (x *FilterRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterRulesResponse.ProtoReflect.Descriptor instead.
func (*FilterRulesResponse) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{2}
}

func (x *FilterRulesResponse) GetRules() []*FilterRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type ForceScrapeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`                    // "BOE", "BOJA", "BOPMA"
	StartDate     string                 `protobuf:"bytes,2,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // YYYY-MM-DD
	EndDate       string                 `protobuf:"bytes,3,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // YYYY-MM-DD
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForceScrapeRequest) Reset() {
	*x = ForceScrapeRequest{}
	mi := &file_scraper_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceScrapeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceScrapeRequest) ProtoMessage() {}

func (x *ForceScrapeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceScrapeRequest.ProtoReflect.Descriptor instead.
func (*ForceScrapeRequest) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{3}
}

func (x *ForceScrapeRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *ForceScrapeRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *ForceScrapeRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type ForceScrapeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ItemsExtracted int32                  `protobuf:"varint,3,opt,name=items_extracted,json=itemsExtracted,proto3" json:"items_extracted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ForceScrapeResponse) Reset() {
	*x = ForceScrapeResponse{}
	mi := &file_scraper_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForceScrapeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceScrapeResponse) ProtoMessage() {}

func (x *ForceScrapeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceScrapeResponse.ProtoReflect.Descriptor instead.
func (*ForceScrapeResponse) Descriptor() ([]byte, []int) {
	return file_scraper_proto_rawDescGZIP(), []int{4}
}

func (x *ForceScrapeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForceScrapeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ForceScrapeResponse) GetItemsExtracted() int32 {
	if x != nil {
		return x.ItemsExtracted
	}
	return 0
}

var File_scraper_proto protoreflect.FileDescriptor

const file_scraper_proto_rawDesc = "" +
	"\n" +
	"\rscraper.proto\x12\ascraper\"\x0e\n" +
	"\fEmptyRequest\"o\n" +
	"\n" +
	"FilterRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x1f\n" +
	"\vfilter_type\x18\x03 \x01(\tR\n" +
	"filterType\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"@\n" +
	"\x13FilterRulesResponse\x12)\n" +
	"\x05rules\x18\x01 \x03(\v2\x13.scraper.FilterRuleR\x05rules\"j\n" +
	"\x12ForceScrapeRequest\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\x12\x1d\n" +
	"\n" +
	"start_date\x18\x02 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x03 \x01(\tR\aendDate\"r\n" +
	"\x13ForceScrapeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fitems_extracted\x18\x03 \x01(\x05R\x0eitemsExtracted2^\n" +
	"\x13FilterConfigService\x12G\n" +
	"\x10GetActiveFilters\x12\x15.scraper.EmptyRequest\x1a\x1c.scraper.FilterRulesResponse2a\n" +
	"\x15ScraperCommandService\x12H\n" +
	"\vForceScrape\x12\x1b.scraper.ForceScrapeRequest\x1a\x1c.scraper.ForceScrapeResponseB4Z\b./protos\xaa\x02'AsistenteAyuntamiento.ApiService.Protosb\x06proto3"

var (
	file_scraper_proto_rawDescOnce sync.Once
	file_scraper_proto_rawDescData []byte
)

func file_scraper_proto_rawDescGZIP() []byte {
	file_scraper_proto_rawDescOnce.Do(func() {
		file_scraper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scraper_proto_rawDesc), len(file_scraper_proto_rawDesc)))
	})
	return file_scraper_proto_rawDescData
}

var file_scraper_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_scraper_proto_goTypes = []any{
	(*EmptyRequest)(nil),        // 0: scraper.EmptyRequest
	(*FilterRule)(nil),          // 1: scraper.FilterRule
	(*FilterRulesResponse)(nil), // 2: scraper.FilterRulesResponse
	(*ForceScrapeRequest)(nil),  // 3: scraper.ForceScrapeRequest
	(*ForceScrapeResponse)(nil), // 4: scraper.ForceScrapeResponse
}
var file_scraper_proto_depIdxs = []int32{
	1, // 0: scraper.FilterRulesResponse.rules:type_name -> scraper.FilterRule
	0, // 1: scraper.FilterConfigService.GetActiveFilters:input_type -> scraper.EmptyRequest
	3, // 2: scraper.ScraperCommandService.ForceScrape:input_type -> scraper.ForceScrapeRequest
	2, // 3: scraper.FilterConfigService.GetActiveFilters:output_type -> scraper.FilterRulesResponse
	4, // 4: scraper.ScraperCommandService.ForceScrape:output_type -> scraper.ForceScrapeResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_scraper_proto_init() }
func file_scraper_proto_init() {
	if File_scraper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scraper_proto_rawDesc), len(file_scraper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_scraper_proto_goTypes,
		DependencyIndexes: file_scraper_proto_depIdxs,
		MessageInfos:      file_scraper_proto_msgTypes,
	}.Build()
	File_scraper_proto = out.File
	file_scraper_proto_goTypes = nil
	file_scraper_proto_depIdxs = nil
}
